export const formInputDatas = [
  {
    label: "暱稱",
    extraInfo: null,
    type: "text",
    id: "name",
    inputName: "nickname",
    inputPlaceholder: "您的回答",
    isRequired: true,
    requiredMessage: "請大爺留下您的芳名",
  },
  {
    label: "電子郵件",
    extraInfo: null,
    type: "email",
    id: "mail",
    inputName: "email",
    inputPlaceholder: "您的電子郵件",
    isRequired: true,
    requiredMessage: "電子郵件也不寫，太呱張了吧 呱呱！！",
  },
  {
    label: "手機號碼",
    extraInfo: null,
    type: "tel",
    id: "cel",
    inputName: "phoneNumber",
    inputPlaceholder: "您的手機號碼",
    isRequired: true,
    requiredMessage: "手機號碼不留，是要我用心電感應逆？",
  },
  {
    label: "報名類型",
    extraInfo: null,
    type: "radio",
    id: "type",
    inputName: "category",
    Options: ["躺在床上用想像力實作", "趴在地上滑手機找現成的"],
    isRequired: true,
    requiredMessage: "報名類型是啥，還不從實招來！",
  },
  {
    label: "怎麼知道這個活動的？",
    extraInfo: null,
    type: "text",
    id: "how",
    inputName: "reason",
    inputPlaceholder: "您的回答",
    isRequired: true,
    requiredMessage: "這題還沒寫完就想偷跑啊，是要逼我出動棒球隊嗎！？",
  },
  {
    label: "其它",
    extraInfo: "對活動的一些建議",
    type: "text",
    id: "others",
    inputName: "advice",
    inputPlaceholder: "您的回答",
    isRequired: false,
  },
];
